FROM arm32v7/openjdk:8-jdk-stretch
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ADD target/*.jar application.jar
EXPOSE 8899
#ENTRYPOINT exec java $JAVA_OPTS -jar discovery-server.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar application.jar